baseURL = "http://example.org/"
defaultContentLanguage = "en"
languageCode = "en"
enableEmoji = true


title = "Blog PJ Mam"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
    footer = "PJ Mam"
    description = "Study, Learn, Learn more ... "
    
    customHeadHTML = """
        <!-- KaTeX -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
        <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
         <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
         <script>
             document.addEventListener("DOMContentLoaded", function() {
             renderMathInElement(document.body, {
             // customised options
             // • auto-render specific keys, e.g.:
              delimiters: [
                {left: '$$', right: '$$', display: true},
                {left: '$', right: '$', display: false},
            ],
            // • rendering keys, e.g.:
             throwOnError : false
        });
      });
    </script>
  """
   socialIcons = [
  
    {name = "linkedin", url = "https://www.linkedin.com/in/phuoc-nguyen-b662891bb/"},
    {name = "instagram", url = "https://www.instagram.com/pj_mam21"},
    {name = "github", url = "https://github.com/pjmam"},
    {name = "email", url = "duyphuocpy2018@gmail.com"}
  ]
 


[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = "<span data-feather='book'></span>"

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 2

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/pjmam"
    weight = 5
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false